"""Quiz format validation.

The Preliminary Project Report documented two recurring failure modes in the
generated quiz: runs that returned fewer than the five questions requested,
and question types falling outside the four intended categories. This module
detects both by inspecting the model's output only. It never changes the
prompt, so the generation behaviour evaluated in the report is untouched and
the failure rate measured here is the failure rate of the evaluated system.

Measuring matters as much as fixing: validation runs even when retry is
disabled, which turns a qualitative observation in the report into a
quantitative result. The functions are pure and dependency-free so the
parsing rules can be unit tested exhaustively without a model.

This module is a measuring instrument, so its target is accuracy rather than
leniency or strictness. Its first contact with real output exposed two ways of
being inaccurate, and both are corrected here:

*   **Under-reporting.** The earlier parser required a label to be exactly
    "Question:" at the start of a line. Real output wrote
    "**Question 1: Definition**", where the number sits inside the label, so
    every block was skipped and a quiz containing five recognisable questions
    was reported as zero. That hid the run's real faults behind a parsing
    failure. Labels are now recognised with an embedded number and surrounding
    markdown.
*   **Over-crediting.** A block whose text is the prompt's own placeholder
    wording ("the question text") is not a question, and an answer line of
    underscores is not an answer. Both were previously counted as present.

Recognising a decorated label never repairs the content behind it. When
"**Question 1: Definition**" is recognised, the word "Definition" is a type
name standing where the question text should be: it is not credited as
question text, and no "Question type:" is inferred from it, because the model
never wrote that line. Both are reported as faults.

Three fault kinds are tracked separately, because "the line is absent", "the
line is present but says nothing" and "the line repeats the prompt back" are
different failures and the Evaluation chapter counts them independently.

The source basis is validated the same way the question type already was,
against the three inputs the system actually accepts. This matters more than a
formatting check: the argument of the whole project is that a student can see
which source produced a statement, so a provenance field naming something that
was never an input undermines the claim the system is built on. Naming the
generated revision notes is reported as its own fault rather than as a plain
miss, because attributing an answer to the system's own first model call is a
different and more interesting failure than naming nothing at all.

The question-shape check is deliberately a warning and never a failure. The
prompt does not literally demand a question mark, so a new soft signal must not
move the pass rate that earlier results were collected under. Warnings are held
separately from failures and `passed` is computed from failures alone.
"""
import re
from dataclasses import dataclass, field

from core.generation import QUIZ_PROMPT

EXPECTED_QUESTION_COUNT = 5
QUESTION_LABEL = "Question"
ANSWER_LABEL = "Suggested answer"
TYPE_LABEL = "Question type"
BASIS_LABEL = "Source basis"
REQUIRED_LABELS = (QUESTION_LABEL, ANSWER_LABEL, TYPE_LABEL, BASIS_LABEL)
# Labels that describe the question currently open. They may appear mid-line;
# see _ATTRIBUTE_PATTERNS for why the question label may not.
ATTRIBUTE_LABELS = (ANSWER_LABEL, TYPE_LABEL, BASIS_LABEL)
VALID_QUESTION_TYPES = ("definition", "explanation", "comparison",
                        "application")

# Fault kinds, kept as constants so they can be counted rather than matched by
# reading the failure text.
MISSING_FAULT = "missing"
EMPTY_FAULT = "empty"
PLACEHOLDER_FAULT = "placeholder"
INVALID_BASIS_FAULT = "invalid_basis"
GENERATED_NOTES_FAULT = "generated_notes_basis"

# The three inputs the system accepts, with the wording the model actually
# uses for each in the saved runs ("Lecture transcript", "Student notes",
# "Slide text" as well as the bare forms the prompt asks for). Matching is on
# these phrases rather than on an exact value, because the prompt asks the
# model to "state whether the answer came mainly from the transcript, the
# slide text or the notes" and it phrases that answer in several ways.
SOURCE_BASIS_TERMS = {
    "transcript": ("transcript",),
    "slide text": ("slide text", "slides", "slide"),
    "notes": ("notes",),
}

# Wording that names the notes generated by the system's own first model call
# rather than an input the student supplied. Checked before the "notes" term
# above, so "Revision notes" is not read as the student notes input.
GENERATED_NOTES_TERMS = ("revision notes", "generated notes",
                         "revision note")

# A question mark is the clearest signal that the text is a question. An
# opening interrogative is a reasonable secondary signal for output that omits
# the mark. Matched on whole words so "state" does not fire on "statement".
INTERROGATIVE_OPENERS = frozenset({
    "what", "why", "how", "which", "when", "where", "who", "whose", "whom",
    "explain", "compare", "contrast", "describe", "define", "discuss",
    "identify", "outline", "state", "give", "list", "name", "calculate",
    "is", "are", "do", "does", "can", "should", "would",
})
# Two-word openers that only read as interrogative together.
INTERROGATIVE_PAIRS = frozenset({"in what", "to what", "under what"})

# Leading decoration a model may put before a label: markdown emphasis, block
# quotes, heading hashes, and list numbering such as "3) ".
_DECORATION = r"[\s>*_#-]*(?:\d+[.)]\s*)?[\s*_#]*"
# A label may carry its own number before the colon, as in "Question 1:".
_LABEL_TAIL = r"\s*\d*\s*:"


def _label_words(label):
    return r"\s+".join(re.escape(word) for word in label.split())


# The question label starts a new block, so it is anchored to the start of a
# line. Starting a block from a mid-line match would let ordinary prose invent
# questions, and the question count is the headline measurement.
_QUESTION_START = re.compile(
    "^" + _DECORATION + _label_words(QUESTION_LABEL) + _LABEL_TAIL,
    re.IGNORECASE)

# Attribute labels are matched anywhere on a line, because real output ran the
# answer label on directly after the question text ("...crucial step?
# Suggested answer: ___"). Attaching an attribute to the block already open
# cannot invent a question, so the risk this tolerance carries is much smaller
# than the risk of anchoring it and mis-scoring every such line as a missing
# answer. The match must still begin at a word boundary.
_ATTRIBUTE_PATTERNS = {
    label: re.compile(
        r"(?:(?<=\s)|^)[*_]*\s*" + _label_words(label) + _LABEL_TAIL,
        re.IGNORECASE)
    for label in ATTRIBUTE_LABELS
}


def _normalise_phrase(text):
    """Lowercase and collapse whitespace for phrase comparison."""
    return re.sub(r"\s+", " ", (text or "").strip().lower()).strip(" .")


def _derive_placeholders():
    """Read the prompt's own placeholder wording out of QUIZ_PROMPT.

    Derived rather than copied so the detection cannot drift: if the prompt's
    template lines are ever reworded, these follow automatically instead of
    silently pointing at wording that no longer exists.
    """
    placeholders = {}
    for line in QUIZ_PROMPT.splitlines():
        stripped = line.strip()
        for label in REQUIRED_LABELS:
            prefix = label + ":"
            if stripped.startswith(prefix):
                value = stripped[len(prefix):].strip()
                if value:
                    placeholders[label] = value
    return placeholders


PROMPT_PLACEHOLDERS = _derive_placeholders()
_NORMALISED_PLACEHOLDERS = {label: _normalise_phrase(value)
                            for label, value in PROMPT_PLACEHOLDERS.items()}


def has_content(value):
    """Return whether a value says anything at all.

    A row of underscores, a dash or a lone punctuation run is a blank waiting
    to be filled in, not an answer, so content requires at least one letter or
    digit.
    """
    return bool(re.search(r"[a-z0-9]", value or "", re.IGNORECASE))


def is_placeholder(label, value):
    """Return whether a value repeats the prompt's own wording for this label.

    Compared for equality rather than containment: a question that merely
    mentions similar words is still a real question, and over-flagging would
    corrupt the measurement as badly as under-flagging.
    """
    expected = _NORMALISED_PLACEHOLDERS.get(label)
    return bool(expected) and _normalise_phrase(value) == expected


def normalise_type(value):
    """Reduce a declared question type to a bare lowercase word.

    Tolerates trailing punctuation and surrounding decoration so that
    "Definition." and "**definition**" both count as the valid type they
    plainly are.
    """
    return re.sub(r"[^a-z]", "", (value or "").lower())


def names_generated_notes(value):
    """Return whether a source basis names the generated revision notes.

    Checked before the input-source terms so "Revision notes" is never read as
    the student notes input; the two differ by one word but mean opposite
    things about where the answer came from.
    """
    text = _normalise_phrase(value)
    return any(term in text for term in GENERATED_NOTES_TERMS)


def basis_sources(value):
    """Return the input sources a source basis names, as a sorted list.

    Any wording that mentions an input counts, so "Lecture transcript" and
    "transcript" both resolve to the transcript, and a combination such as
    "notes, slide text" resolves to both. An empty list means the value named
    no input at all.
    """
    text = _normalise_phrase(value)
    if names_generated_notes(text):
        # Strip the generated-notes wording first so its trailing "notes" is
        # not then counted as the student notes input.
        for term in GENERATED_NOTES_TERMS:
            text = text.replace(term, " ")
    found = [source for source, terms in SOURCE_BASIS_TERMS.items()
             if any(term in text for term in terms)]
    return sorted(found)


def looks_like_a_question(value):
    """Return whether question text has the shape of a question.

    A question mark is the primary signal; an opening interrogative is a
    secondary one for output that omits the mark. This is a soft check whose
    result is reported as a warning and never as a validation failure.
    """
    if "?" in (value or ""):
        return True
    words = re.findall(r"[a-z]+", _normalise_phrase(value))
    if not words:
        return False
    if words[0] in INTERROGATIVE_OPENERS:
        return True
    return " ".join(words[:2]) in INTERROGATIVE_PAIRS


def _is_bare_type_word(value):
    """Return whether a value is nothing but one of the four type names.

    "**Question 1: Definition**" puts a category name where the question text
    belongs. That is a heading, not a question, so it is not accepted as
    question text. The rule is deliberately narrow: only a value consisting of
    a type name alone is rejected, so a real question that happens to begin
    with "Comparison of ..." still counts.
    """
    return normalise_type(value) in VALID_QUESTION_TYPES


@dataclass
class QuestionBlock:
    """One parsed question and what was wrong with it."""
    number: int
    fields: dict = field(default_factory=dict)
    seen_labels: set = field(default_factory=set)
    missing_labels: list = field(default_factory=list)
    empty_labels: list = field(default_factory=list)
    placeholder_labels: list = field(default_factory=list)
    # Source basis faults, held as fault-kind constants rather than label
    # names because both concern the same label for different reasons.
    basis_faults: list = field(default_factory=list)
    # Soft signals. Never part of faults, so they cannot change the verdict.
    shape_warnings: list = field(default_factory=list)

    @property
    def declared_type(self):
        return self.fields.get(TYPE_LABEL, "")

    @property
    def declared_basis(self):
        return self.fields.get(BASIS_LABEL, "")

    @property
    def type_is_valid(self):
        return normalise_type(self.declared_type) in VALID_QUESTION_TYPES

    @property
    def basis_is_valid(self):
        return bool(basis_sources(self.declared_basis))

    @property
    def faults(self):
        return (self.missing_labels + self.empty_labels
                + self.placeholder_labels + self.basis_faults)

    @property
    def is_complete(self):
        """No label absent, blank, echoed back from the prompt, or naming a
        source that was never an input. Warnings are excluded by design."""
        return not self.faults


@dataclass
class QuizValidation:
    """Structured verdict on one generated quiz.

    Carries the detail the Evaluation chapter needs (how many questions, which
    checks failed and why), not just a pass or fail flag.
    """
    questions_found: int
    blocks: list = field(default_factory=list)
    failures: list = field(default_factory=list)
    # Soft signals, held apart from failures on purpose: passed is computed
    # from failures alone, so a warning can never change a verdict.
    warnings: list = field(default_factory=list)

    @property
    def returned_five(self):
        return self.questions_found == EXPECTED_QUESTION_COUNT

    @property
    def passed(self):
        return not self.failures

    @property
    def shape_warning_count(self):
        return sum(len(block.shape_warnings) for block in self.blocks)

    def count_faults(self, kind):
        """Count one kind of fault across all blocks, so each can be reported
        separately in the evaluation tables."""
        if kind in (INVALID_BASIS_FAULT, GENERATED_NOTES_FAULT):
            return sum(block.basis_faults.count(kind)
                       for block in self.blocks)
        attribute = {
            MISSING_FAULT: "missing_labels",
            EMPTY_FAULT: "empty_labels",
            PLACEHOLDER_FAULT: "placeholder_labels",
        }[kind]
        return sum(len(getattr(block, attribute)) for block in self.blocks)

    def describe_warnings(self):
        """One-line summary of the soft signals, for the columns that report
        them alongside (never inside) the failure text."""
        return "; ".join(self.warnings)

    def describe(self):
        """One-line summary for the saved run header and CSV columns."""
        if self.passed:
            return f"passed ({self.questions_found} questions)"
        return "; ".join(self.failures)


def _clean_value(text):
    """Trim a captured value and drop surrounding markdown emphasis."""
    return (text or "").strip().strip("*_ ").strip()


def _scan_line(line):
    """Split one line into (text before the first label, [(label, value)]).

    The question label is recognised only at the start of a line; attribute
    labels are recognised anywhere. Overlapping matches are dropped so a label
    cannot be counted twice.
    """
    matches = []
    start_match = _QUESTION_START.match(line)
    if start_match:
        matches.append((start_match.start(), start_match.end(),
                        QUESTION_LABEL))
    for label in ATTRIBUTE_LABELS:
        found = _ATTRIBUTE_PATTERNS[label].search(line)
        if found:
            matches.append((found.start(), found.end(), label))
    matches.sort(key=lambda item: item[0])

    kept = []
    last_end = 0
    for start, end, label in matches:
        if start >= last_end:
            kept.append((start, end, label))
            last_end = end
    if not kept:
        return line, []

    leading = line[:kept[0][0]]
    segments = []
    for index, (_start, end, label) in enumerate(kept):
        stop = kept[index + 1][0] if index + 1 < len(kept) else len(line)
        segments.append((label, line[end:stop]))
    return leading, segments


def parse_quiz(quiz_text):
    """Parse quiz text into QuestionBlocks.

    A question label starts a new block; attribute labels attach to the block
    currently open. An unlabelled line continues the value most recently
    opened, because real output puts the question text on the line after the
    heading. Content before the first question label (a stray preamble) is
    ignored rather than treated as a question.
    """
    blocks = []
    current = None
    current_label = None
    for line in (quiz_text or "").splitlines():
        leading, segments = _scan_line(line)
        if leading.strip() and current is not None and current_label:
            # Continuation of the value already being collected.
            joined = (current.fields.get(current_label, "") + "\n"
                      + leading.strip()).strip()
            current.fields[current_label] = joined
        for label, value in segments:
            if label == QUESTION_LABEL:
                current = QuestionBlock(number=len(blocks) + 1)
                blocks.append(current)
                current.fields[QUESTION_LABEL] = _clean_value(value)
                current.seen_labels.add(QUESTION_LABEL)
                current_label = QUESTION_LABEL
            elif current is not None:
                if label not in current.seen_labels:
                    current.fields[label] = _clean_value(value)
                    current.seen_labels.add(label)
                current_label = label

    for block in blocks:
        _classify_faults(block)
    return blocks


def _classify_faults(block):
    """Sort each required label into absent, blank, echoed or acceptable."""
    for label in REQUIRED_LABELS:
        if label not in block.seen_labels:
            block.missing_labels.append(label)
            continue
        value = block.fields.get(label, "")
        if is_placeholder(label, value):
            block.placeholder_labels.append(label)
        elif not has_content(value):
            block.empty_labels.append(label)
        elif label == QUESTION_LABEL and _is_bare_type_word(value):
            # A category name standing in for the question text is a heading,
            # not a question, so the question text counts as absent.
            block.empty_labels.append(label)

    _classify_basis(block)
    _classify_shape(block)


def _classify_basis(block):
    """Check that the source basis names an input the student supplied.

    Only runs when the label carries real content: an absent, blank or echoed
    basis is already reported by _classify_faults, and reporting it twice
    would inflate the fault statistics.
    """
    if BASIS_LABEL not in block.seen_labels:
        return
    if (BASIS_LABEL in block.empty_labels
            or BASIS_LABEL in block.placeholder_labels):
        return
    value = block.declared_basis
    if names_generated_notes(value):
        # Distinct fault: this attributes the answer to the notes the system
        # generated in its own first model call, not to any supplied input.
        block.basis_faults.append(GENERATED_NOTES_FAULT)
    elif not basis_sources(value):
        block.basis_faults.append(INVALID_BASIS_FAULT)


def _classify_shape(block):
    """Warn when the question text does not read as a question.

    A warning, never a fault: the prompt asks for questions but does not
    literally require a question mark, so this must not move the pass rate
    that earlier results were collected under.
    """
    if QUESTION_LABEL not in block.seen_labels:
        return
    if (QUESTION_LABEL in block.empty_labels
            or QUESTION_LABEL in block.placeholder_labels):
        return
    if not looks_like_a_question(block.fields.get(QUESTION_LABEL, "")):
        block.shape_warnings.append(QUESTION_LABEL)


def _label_list(labels):
    return ", ".join(f"'{label}:'" for label in labels)


def validate_quiz(quiz_text, expected_count=EXPECTED_QUESTION_COUNT):
    """Validate generated quiz text against the format the prompt requests.

    Checks exactly five questions, all four labelled lines present on each and
    carrying real content rather than a blank or the prompt's own placeholder
    wording, and every declared question type inside the four intended
    categories. Returns a QuizValidation carrying the detail of what failed.
    """
    blocks = parse_quiz(quiz_text)
    failures = []
    warnings = []

    if len(blocks) != expected_count:
        failures.append(
            f"expected {expected_count} questions, found {len(blocks)}")

    for block in blocks:
        if block.missing_labels:
            failures.append(f"question {block.number} missing "
                            + _label_list(block.missing_labels))
        if block.empty_labels:
            failures.append(f"question {block.number} has an empty "
                            + _label_list(block.empty_labels))
        if block.placeholder_labels:
            failures.append(
                f"question {block.number} repeats the prompt placeholder for "
                + _label_list(block.placeholder_labels))
        # A type that is absent, blank or echoed is already reported above;
        # only a real but wrong value is reported here, so one fault is never
        # counted twice in the failure statistics.
        if (TYPE_LABEL in block.seen_labels
                and TYPE_LABEL not in block.empty_labels
                and TYPE_LABEL not in block.placeholder_labels
                and not block.type_is_valid):
            failures.append(
                f"question {block.number} has invalid type "
                f"'{block.declared_type}'")
        if GENERATED_NOTES_FAULT in block.basis_faults:
            failures.append(
                f"question {block.number} attributes its source basis to the "
                f"generated revision notes ('{block.declared_basis}'), not to "
                "a supplied input")
        if INVALID_BASIS_FAULT in block.basis_faults:
            failures.append(
                f"question {block.number} has a source basis naming no input "
                f"source '{block.declared_basis}'")
        if block.shape_warnings:
            warnings.append(
                f"question {block.number} does not read as a question")

    return QuizValidation(questions_found=len(blocks), blocks=blocks,
                          failures=failures, warnings=warnings)
